spring:
  data:
    elasticsearch:
      ####集群名称
      cluster-name: my-application
      ####地址
      cluster-nodes: 127.0.0.1:9301,127.0.0.1:9302,127.0.0.1:9303
xxl:
  job:
    accessToken:
    executor:
      appname: demo
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999
      address:
    admin:
      addresses: http://127.0.0.1:8070/xxl-job-admin

server:
  port: 8082